apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cephdaemons.ceph.k8s.pgc.umn.edu
spec:
  group: ceph.k8s.pgc.umn.edu
  names:
    kind: CephDaemon
    listKind: CephDaemonList
    plural: cephdaemons
    singular: cephdaemon
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
