---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ceph-operator-osd
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ceph-operator-osd
subjects:
- kind: ServiceAccount
  name: ceph-operator-osd
  namespace: ceph-testing
roleRef:
  kind: ClusterRole
  name: ceph-operator-osd
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ceph-operator-osd
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - 'get'
